name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]  # Added Ubuntu support

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 requests
        pip install pillow  # Added Pillow for automatic conversion on macOS
    
    # Linux-specific dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender1
    
    # Build step without conditional
    - name: Build with PyInstaller
      run: |
        pyinstaller --name JokeNotifier --windowed --onefile --icon=images/app.ico joke_notifier.py
    
    # Windows artifact upload
    - name: Upload Windows artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: JokeNotifier-${{ matrix.os }}
        path: dist/*.exe

    # macOS artifact upload
    - name: Upload macOS artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: JokeNotifier-${{ matrix.os }}
        path: dist/*.app

    # Linux artifact upload
    - name: Upload Linux artifacts
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: JokeNotifier-${{ matrix.os }}
        path: dist/JokeNotifier