name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 requests
        # Add any other dependencies here
    - name: Build with PyInstaller
      run: |
        pyinstaller --name JokeNotifier --windowed --onefile --icon=images/app.ico joke_notifier.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: JokeNotifier-${{ matrix.os }}
        path: |
          dist/*.exe
          dist/*.app
